services:
  backend:
    build:
      context: ./backend
    container_name: clock_portal_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8010
    environment:
      APP_CORS_ORIGINS: http://localhost:80,http://127.0.0.1:80
    expose:
      - "8010"

  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: clock_portal_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

